version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100" # O "0.0.0.0" força o Docker a escutar em TODAS as placas de rede
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - tcc-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: root
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    networks:
      - tcc-network
    depends_on:
      - loki

  alerts-api:
    build: ./alerts-api
    container_name: alerts-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./alerts-api:/app
    networks:
      - tcc-network
    env_file:
      - .env 

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_tcc
    restart: unless-stopped
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - tcc-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma_vector_db
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    networks:
      - tcc-network

  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - alerts-api
      - grafana
    networks:
      - tcc-network

  # TÚNEL 1: O Painel Principal (Frontend Streamlit)
  ngrok-frontend:
      image: ngrok/ngrok:latest
      container_name: ngrok-frontend
      restart: unless-stopped
      environment:
        - NGROK_AUTHTOKEN=3CN8gEwSvjAUlit4UG1PZ4YTCeC_2GaFz4sstrPEyWyY3dTfU
      command:
        - "http"
        - "frontend:8501"
      ports:
        - "4040:4040"
      networks:
        - tcc-network 
      depends_on:
        - frontend
        - ngrok-grafana

  # TÚNEL 2: O Iframe Oculto (Grafana)
  ngrok-grafana:
    image: ngrok/ngrok:latest
    container_name: ngrok-grafana
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=3EXYZ0tlCDHieF0dvDUEFDT2sDn_6FXC9TFFC2GsZZG4jpzdK
    command:
      - "http"
      - "grafana:3000"
    ports:
      - "4041:4040"
    networks:
      - tcc-network 
    depends_on:
      - grafana

volumes:
  ollama_data:
  grafana_data:

networks:
  tcc-network:
    driver: bridge